#!/bin/sh

if [ -z "$USER" ]; then
    USER=$(id -un)
fi

echo >&2 "====================================================================="
echo >&2 " Setting up codespaces environment"
echo >&2 ""
echo >&2 " USER        $USER"
echo >&2 " HOME        $HOME"
echo >&2 "====================================================================="

cd $HOME

mkdir -p $HOME/bin

sudo apt-get update
sudo apt-get install -y zsh
sudo apt-get install ripgrep
sudo chsh -s /usr/bin/zsh $USER

# Make passwordless sudo work
export SUDO_ASKPASS=/bin/true

# Install fzf
curl -L https://github.com/junegunn/fzf/releases/download/v0.55.0/fzf-0.55.0-linux_amd64.tar.gz | tar xzC $HOME/bin

# Install neovim

mkdir -p $HOME/bin/nvim
sudo apt-get install -y libfuse2
curl -L -o $HOME/bin/nvim https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
chmod a+x $HOME/bin/nvim

cp -r ./.config/* $HOME/.config/.
cp -f ./.zshrc $HOME/.zshrc
